name = "DiplodocusPlots"
uuid = "e2feba3a-3769-4cd4-93ab-3db026c329dd"
version = "0.2.0"
authors = ["Christopher Everett <cn.everett@outlook.com> and contributors"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DiplodocusCollisions = "32d0d58a-4da0-4f8e-8b7e-c2816ac6e5cb"
DiplodocusTransport = "f63b9913-7a9a-464d-82b9-3e1e536d6db0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
CairoMakie = "0.13.7"
DiplodocusCollisions = "0.1"
DiplodocusTransport = "0.2, 0.1"
GLMakie = "0.11.8"
Revise = "3.8.0"
julia = "1.12.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
